from typing import Literal, TypeAlias

SemanticRecord: TypeAlias = tuple[int, int, int, int | None, bytes]

class ScanSummary:
    @property
    def format(self) -> int: ...
    @property
    def tracks(self) -> int: ...
    @property
    def division(self) -> int: ...
    @property
    def events(self) -> int: ...
    @property
    def channel_events(self) -> int: ...
    @property
    def meta_events(self) -> int: ...
    @property
    def sysex_events(self) -> int: ...
    @property
    def payload_bytes(self) -> int: ...
    @property
    def max_delta_ticks(self) -> int: ...
    @property
    def bytes_consumed(self) -> int: ...
    @property
    def trailing_bytes(self) -> int: ...

class MidiFile:
    def __init__(self, data: bytes, /) -> None: ...
    @property
    def format(self) -> int: ...
    @property
    def track_count(self) -> int: ...
    @property
    def division(self) -> int: ...
    @property
    def event_count(self) -> int: ...
    @property
    def heap_bytes(self) -> int: ...
    @property
    def bytes_consumed(self) -> int: ...
    @property
    def trailing_bytes(self) -> int: ...
    @property
    def track_lengths(self) -> list[int]: ...
    def semantic_records(self) -> list[SemanticRecord]: ...
    def __len__(self) -> int: ...

class ScoreParseLimits:
    def __init__(
        self,
        *,
        max_input_bytes: int = 67108864,
        max_source_tracks: int = 4096,
        max_track_bytes: int = 16777216,
        max_events: int = 2000000,
        max_note_starts: int = 1000000,
        max_text_bytes: int = 16777216,
    ) -> None: ...
    @property
    def max_input_bytes(self) -> int: ...
    @property
    def max_source_tracks(self) -> int: ...
    @property
    def max_track_bytes(self) -> int: ...
    @property
    def max_events(self) -> int: ...
    @property
    def max_note_starts(self) -> int: ...
    @property
    def max_text_bytes(self) -> int: ...

class Score:
    def __init__(
        self,
        data: bytes,
        /,
        *,
        limits: ScoreParseLimits | None = None,
        mode: Literal["compatible", "strict"] = "compatible",
    ) -> None: ...
    @property
    def ticks_per_quarter(self) -> int: ...
    @property
    def track_count(self) -> int: ...
    @property
    def note_count(self) -> int: ...
    @property
    def control_count(self) -> int: ...
    @property
    def pitch_bend_count(self) -> int: ...
    @property
    def pedal_count(self) -> int: ...
    @property
    def lyric_count(self) -> int: ...
    @property
    def time_signature_count(self) -> int: ...
    @property
    def key_signature_count(self) -> int: ...
    @property
    def tempo_count(self) -> int: ...
    @property
    def marker_count(self) -> int: ...
    @property
    def heap_bytes(self) -> int: ...
    @property
    def bytes_consumed(self) -> int: ...
    @property
    def trailing_bytes(self) -> int: ...
    def semantic_records(self) -> dict[str, object]: ...
    def __len__(self) -> int: ...

def parse(data: bytes, /) -> MidiFile: ...
def parse_score(
    data: bytes,
    /,
    *,
    limits: ScoreParseLimits | None = None,
    mode: Literal["compatible", "strict"] = "compatible",
) -> Score: ...
def parse_score_unlimited(data: bytes, /) -> Score: ...
def scan(data: bytes, /) -> ScanSummary: ...
